---
title: "ISYE6501 HW2"
author: "Keh-Harng Feng"
date: "May 29, 2017"
output: 
  bookdown::pdf_book:
    fig_caption: TRUE
    toc: FALSE
urlcolor: blue
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, tidy = TRUE, cache = TRUE)
options(digits = 4)

library('caret')
library('corrplot')
```

## Preface
This is a reproducible report with most of the codes doing the heavy lifting hidden in the background. **All codes are available to be audited.** If you wish to check the various scripts and code snippets used for the computations, you can download the source code of the report by [clicking here](https://github.com/fengkehh/ISYE6501WK3/blob/master/HW3_Report.Rmd). However, as a general rule of thumb you should NOT run any downloaded R scripts from an untrusted source on your computer without understanding the source code first.

# Question 1
**Describe a situation or problem from your job, everyday life, current events, etc., for which exponential smoothing would be appropriate. What data would you need? Would you expect the value of $\alpha$ (the first smoothing parameter) to be closer to 0 or 1, and why?**

I worked on a computer model that simulates the transfer of radiation through the atmosphere. Clearly the amount of radiation that reaches the surface will depend on things such as the incident angle and the amount of radiation that reaches the top of the atmosphere. The current incident angle can be computed based on the orbital characteristics between the Earth and the Sun. However, the exact amount of energy outputted by the sun is highly dependent on solar activities and is not a simple task to model using physics. If data is lacking for a particular period of interest we can use exponential smoothing to produce an estimation. 

Data required would be the measured top of the atmosphere solar irradiance in $W/m^2$ set at a reference distance at a fixed time step size. Note that the Earth's orbit is not circular and thus the distance between the Earth and the Sun will change constantly. Nevertheless it is very easy to work backwards to compute the irradiance at a reference distance by knowing the exact spot Earth and the measuring satellite are at currently and assuming isotropic radiation from the Sun. 

Judging by [this chart](https://smd-prod.s3.amazonaws.com/science-red/s3fs-public/mnt/medialibrary/2013/01/08/tsi_composite_strip.jpg) there is some form of seasonality on the time scale of decades. If data is measured monthly it would be best to set $\alpha$ to a  small number since the time scale that is really of interest is much larger than the time step.

# Question 2
**Using the 20 years of daily high temperature data for Atlanta (July through October) from Homework 2 Question 5, build and use an exponential smoothing model to help make a judgment of whether the unofficial end of summer has gotten later over the 20 years. (Part of the point of this assignment is for you to think about how you might use exponential smoothing to answer this question.) Note: in R, you can use either HoltWinters (simpler to use) or the smooth package’s es function (harder to use, but more general). If you use es, the Holt-Winters model uses model=”AAM” in the function call (the first and second constants are used “A”dditively, and the third (seasonality) is used “M”ultiplicatively; the documentation doesn’t make that clear).**



# Question 3
**Describe a situation or problem from your job, everyday life, current events, etc., for which a linear regression model would be appropriate. List some (up to 5) predictors that you might use.**

Recently I completed a project that involves analyzing the effects of different factors on automobile fuel efficiency. The data includes measured fuel effciency of different vehicles in the forms of miles per gallon and various physical characteristics of the cars. The main question was if the types of transmission (auto or manual) had an effect on fuel effciency. My strategy to answer that question was to build a multivariate linear regression model to fit MPG on pertinent predictors and see if transmission type was a significant predictor in the model. The following predictors were chosen after feature selection:

`Transmission Type`

`Number of Engine Cylinders`

`Weight`

`Horsepower`

Hypothesis test carried out on model coefficients showed that transmission is NOT an important factor when it comes to fuel efficiency. The full report can be accessed [here](https://fengkehh.github.io/post/2017-03-30-can-car-transmission-affect-fuel-efficiency/).

# Question 4

**Using crime data from http://www.statsci.org/data/general/uscrime.txt (description at http://www.statsci.org/data/general/uscrime.html ), use regression (a useful R function is lm or glm) to predict the observed crime rate in a city with [the data shown on handout].**

**Show your model (factors used and their coefficients), the software output, and the quality of fit.**

## Data Preprocess

TODO: Strategy -- show there are no near zero variance predictors. Show pair matrix plot. Show strong correlation between P01 and P02 using corrPlot. Use findCorrelation to identify P01 as the predictor to be removed (reference Kuhn for algorithm). 

Scale & center.

## Feature Selection

Split preprocessed data into test & training.

Using training set:
Iterate through all predictor combinations. Each iteration: estimate out-of-sample performance using 10-fold cross validation (sample size too small?) and MSE? Or use AIC?

Choose best combination. 

## Performance Evaluation

Retrain using full training set. Compute prediction on test set & show R^2 or MSE.

## Prediction

Make prediction using specified predictor values.
